//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DTMF_Decoder.rc
//
#define IDC_MYICON                      2
#define IDD_DTMFDECODER_DIALOG          102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDS_GOERTZEL_FAILED_TO_SET_MMCSS 104
#define IDM_EXIT                        105
#define IDS_GOERTZEL_WAITFORSINGLEOBJECT_FAILED 105
#define IDS_GOERTZEL_WAITFORSINGLEOBJECT_FAILED_UNKNOWN 106
#define IDI_DTMF_DECODER                107
#define IDS_GOERTZEL_FAILED_TO_REVERT_MMCSS 107
#define IDS_GOERTZEL_DONE               108
#define IDC_DTMFDECODER                 109
#define IDS_GOERTZEL_START              110
#define IDS_GOERTZEL_CLOSE_STARTDFT_HANDLES 111
#define IDS_GOERTZEL_CLOSE_DONEDFT_HANDLES 112
#define IDS_GOERTZEL_ENDED_NORMALLY     113
#define IDS_GOERTZEL_THREAD_END_FAILED  114
#define IDS_GOERTZEL_FAILED_TO_SIGNAL_START_DFT 115
#define IDS_GOERTZEL_FAILED_TO_CREATE_STARTDFT_HANDLES 116
#define IDS_GOERTZEL_FAILED_TO_CREATE_DONEDFT_HANDLES 117
#define IDS_GOERTZEL_FAILED_TO_CREATE_WORK_THREAD 118
#define IDS_MODEL_FAILED_TO_MALLOC      119
#define IDS_MODEL_FAILED_TO_INVALIDATE_REGION 120
#define IDS_MODEL_FAILED_TO_INVALIDATE_COLUMN 121
#define IDS_MODEL_FAILED_TO_INVALIDATE_ROW 122
#define IDS_DTMF_DECODER_FAILED_TO_GET_MESSAGE 123
#define IDS_DTMF_DECODER_FAILED_TO_PAINT 124
#define IDS_DTMF_DECODER_FAILED_TO_END_PAINT 125
#define IDS_DTMF_DECODER_FAILED_TO_SIGNAL_gAUDIOSAMPLESREADY 126
#define IDS_DTMF_DECODER_FAILED_TO_STOP_AUDIO_DEVICE 127
#define IDR_MAINFRAME                   128
#define IDS_DTMF_DECODER_FAILED_TO_DESTROY_WINDOW 128
#define IDS_DTMF_DECODER_FAILED_TO_CLEANUP_VIEW 129
#define IDS_DTMF_DECODER_ABOUT_FAILED_TO_SET_NAME 130
#define IDS_DTMF_DECODER_ABOUT_FAILED_TO_SET_DATE 131
#define IDS_DTMF_DECODER_ABOUT_FAILED_TO_END 132
#define IDS_DTMF_DECODER_FAILED_TO_INITIALIZE_COM 133
#define IDS_DTMF_DECODER_STARTING       134
#define IDS_DTMF_DECODER_FAILED_TO_RETRIEVE_TITLE 135
#define IDS_DTMF_DECODER_FAILED_TO_RETRIEVE_CLASS_NAME 136
#define IDS_DTMF_DECODER_FAILED_TO_REGISTER_WINDOW_CLASS 137
#define IDS_DTMF_DECODER_FAILED_TO_CREATE_MAIN_WINDOW 138
#define IDS_DTMF_DECODER_CREATED_MAIN_WINDOW 139
#define IDS_DTMF_DECODER_FAILED_TO_REGISTER_CUSTOM_MESSAGE 140
#define IDS_DTMF_DECODER_FAILED_TO_INITIALIZE_MODEL 141
#define IDS_DTMF_DECODER_FAILED_TO_INITIALIZE_VIEW 142
#define IDS_DTMF_DECODER_FAILED_TO_INITIALIZE_AUDIO 143
#define IDS_DTMF_DECODER_FAILED_TO_LOAD_MENU 144
#define IDS_DTMF_DECODER_APP_RESOURCES_READY 145
#define IDS_DTMF_DECODER_FAILED_TO_END_DFT_THREADS 146
#define IDS_DTMF_DECODER_FAILED_TO_CLEANUP_AUDIO 147
#define IDS_DTMF_DECODER_FAILED_TO_CLEANUP_DFT 148
#define IDS_DTMF_DECODER_FAILED_TO_CLEANUP_MODEL 149
#define IDS_DTMF_DECODER_FAILED_TO_CLEANUP_LOGS 150
#define IDS_DTMF_DECODER_ENDING_SUCCESSFULLY 151
#define IDS_DTMF_DECODER_ENDING_IN_FAILURE_MODE 152
#define IDS_GOERTZEL_SET_MMCSS          153
#define IDS_STRING154                   154
#define IDS_STRING155                   155
#define IDS_STRING156                   156
#define IDS_STRING157                   157
#define IDS_STRING158                   158
#define IDS_STRING159                   159
#define IDS_STRING160                   160
#define IDS_STRING161                   161
#define IDS_STRING162                   162
#define IDC_PROGRAM_NAME                1000
#define IDC_AUTHOR                      1001
#define IDC_COPYRIGHT                   1002
#define IDC_DATE                        1002
#define IDC_COPYRIGHT2                  1003
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
